In [1]:
import numpy as np


In [43]:
%%latex
\begin{equation*}
N_{SR}^{Data} = N_{signal}^{MC} + N_{TTinSR}^{MC}*SF_{TT} + N_{DYJetsinSR}^{MC}*SF_{DYJets} + O(\%)
\end{equation*}

<IPython.core.display.Latex object>

In [32]:
%%latex
\begin{equation*}
N_{CR_{TT}}^{Data} = 0 + N_{TTinCR_{TT}}^{MC}*SF_{TT} + O(\%)
\end{equation*}

<IPython.core.display.Latex object>

In [44]:
%%latex
\begin{equation*}
N_{CR_{DYJets}}^{Data} =  \%(N_{TTinDY_{CR}}^{MC}*SF_{TT}) + N_{DYJetsinCR}^{MC}*SF_{DYJets} + O(\%)
\end{equation*}

<IPython.core.display.Latex object>

In [45]:
#example: signal + TT + DY = N_of_events in data

# SR=low signal, DY and TT are 50/50: 0.1x + 10y +10z = 10
# CR_TT=no signal, no DY, just TT: 0x + 9y+ 0z = 5
#CR_DY=no signal, mostly DY, a bit of TT: 0x + 1y + 9z = 5

# A * {x,y,z} = b

In [67]:
%%latex
\begin{equation*}
\begin{vmatrix}
\mathbf{i_{1}} & \mathbf{j_{1}} & \mathbf{k_{1}} \\
\mathbf{i_{2}} & \mathbf{j_{2}} & \mathbf{k_{2}} \\
\mathbf{i_{3}} & \mathbf{j_{3}} & \mathbf{k_{3}} \\
\end{vmatrix} * 
\begin{vmatrix}
\mathbf{x_{1}}  \\
\mathbf{x_{2}} \\
\mathbf{x_{3}} \\
\end{vmatrix}
= 
\begin{vmatrix}
\mathbf{b_{1}}  \\
\mathbf{b_{2}} \\
\mathbf{b_{3}} \\
\end{vmatrix}

\end{equation*}

<IPython.core.display.Latex object>

In [70]:
A = np.array([[0.1, 10, 10],[0, 9, 0],[0, 1, 9]])
A

array([[  0.1,  10. ,  10. ],
       [  0. ,   9. ,   0. ],
       [  0. ,   1. ,   9. ]])

In [71]:
b = np.array([10, 5, 5])
b

array([10,  5,  5])

In [73]:
x = np.linalg.solve(A,b)
x

array([-4.9382716 ,  0.55555556,  0.49382716])

In [78]:
checkSolution = np.dot(A,x)
checkSolution == b

array([ True,  True,  True], dtype=bool)